---
detectors:
  UncommunicativeVariableName:
    accept:
      - t
  IrresponsibleModule:
    enabled: false

directories:
  "db/migrate":
    TooManyStatements:
      enabled: false
    FeatureEnvy:
      enabled: false

exclude_paths:
  - db/seeds.rb
  - db/printer.rb
  - db/seeds/journey.rb
  - db/seeds/assessment_builder.rb
  - spec/mailers/previews/crisis_event_mailer_preview.rb