---
detectors:
  UncommunicativeVariableName:
    accept:
      - t
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    max_calls: 3
    exclude:
      - time_between
  NilCheck:
    exclude:
      - subheading_stats
  FeatureEnvy:
    exclude:
      - journal_entry_search
      - time_between
      - answer_pct
  TooManyInstanceVariables:
    max_instance_variables: 10
    exclude:
      - UsersController
      - WellbeingAssessmentsController
  TooManyMethods:
    exclude:
      - AffirmationsController
      - SurveysController
      - UsersController
      - WellbeingAssessmentsController
      - AppointmentsController
  TooManyStatements:
    max_statements: 10
    exclude:
      - show
      - new
      - update
      - JournalEntriesController
      - score_description
  UtilityFunction:
    public_methods_only: true
  ControlParameter:
    exclude:
      - success
      - AchievementsHelper
      - WellbeingAssessmentsHelper

directories:
  "db/migrate":
    TooManyStatements:
      enabled: false
    FeatureEnvy:
      enabled: false
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
    LongParameterList:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false

exclude_paths:
  - db/config.rb
  - db/seeds.rb
  - db/printer.rb
  - db/seeds/journey.rb
  - db/seeds/assessment_builder.rb
  - spec/mailers/previews/crisis_event_mailer_preview.rb
  - app/controllers/concerns/accessible.rb
  - app/controllers/concerns/exportable.rb
  - app/controllers/concerns/pagination.rb