AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'bin/{rails,rake,yarn,bundle}'
    - 'lib/tasks/*'
    - 'test/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Exclude:
    - 'db/seeds.rb'
    - 'db/seeds/*'
Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/Documentation:
  Exclude:
    - 'app/helpers/*'


