# db/config
module Config
  TOTAL_USER_COUNT = 10
  WELLBEING_ASSESSMENTS_FOR_EACH_USER = 20
  JOURNAL_ENTRIES_FOR_EACH_USER = 5
  CONTACTS_FOR_EACH_USER = 5
  APPOINTMENTS_FOR_EACH_USER = 20
  PAST_APPOINTMENTS_FOR_EACH_USER = 20
  NOTES_COUNT = 100
  GOALS_FOR_EACH_USER = 10 # Half short-term, half long-term
  CRISIS_EVENTS_COUNT = 20
  CRISIS_NOTES_COUNT = 20
end
